# Generated by Django 5.2.7 on 2025-11-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0002_alter_agendamentos_fisioterapia_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendamentos_psicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('data_e_hora', models.DateTimeField()),
                ('tipo_de_consulta', models.CharField(max_length=20)),
                ('pdsp', models.CharField(max_length=20)),
            ],
        ),
    ]
